### ISSUE TITLE
Question: UDP vs TCP

### ISSUE THREAD

**Issue by naiteon** [colyseus/create-colyseus-app#9]
Is there any chance you could be using UDP instead of TCP in a near future?

**Comment by seiyria** [comment]
UDP has been brought up many times before but there are no plans to go forward with it at this time as far as I know.

**Comment by endel** [comment]
A potential UDP implementation is being tracked here https://github.com/colyseus/colyseus/issues/272

As @seiyria mentioned there are no immediate plans to make this happen because of the complexity involved. There are other aspects of the framework that needs attention first, such as improving the way to scale it
